config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :houses, only: [:show] do
    resources :monsters, only: [:new, :create]
  end
  resources :monsters, only: [:destroy] do
    resources :curses, only: [:new, :create]
  end
end
# As a user I can see one haunted house's monsters
# houses#show
# get '/houses/:id', to: 'houses#show', as: :house

# As a user I can condemn a monster in a haunted house
# monsters#new / monsters#create
# get 'houses/:house_id/monsters/new'
# post 'houses/:house_id/monsters'

# As a user I can release a monster
# monsters#destroy
# delete 'monsters/:id'

# As a user I add a power to a monster (creating a curse)
# curses#new/create
# get 'monsters/:monster_id/curses/new'
# post 'monsters/:monster_id/curses'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/curse.rb
class Curse < ApplicationRecord
  belongs_to :monster
  belongs_to :power
  validates :monster, uniqueness: { scope: :power }
end

app/models/house.rb
class House < ApplicationRecord
  has_many :monsters, dependent: :destroy
  validates :name, presence: true
end

app/models/monster.rb
class Monster < ApplicationRecord
  belongs_to :house
  has_many :curses, dependent: :destroy
  has_many :powers, through: :curses
  validates :name, presence: true
  # this allows us to save the key on the instance
  has_one_attached :photo # .photo -> .photo.key
end

app/models/power.rb
class Power < ApplicationRecord
  has_many :curses # creates the method (power.curses)
  has_many :monsters, through: :curses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/curses_controller.rb
class CursesController < ApplicationController
  # get '/monsters/:monster_id/curses/new'
  def new
    @monster = Monster.find(params[:monster_id])
    @curse = Curse.new
    # @powers = Power.order(name: :asc)
    # @powers = @monster.powers
    @powers = Power.where.not(id: @monster.powers).order(name: :asc)
  end

  # post '/monsters/:monster_id/curses'
  def create
    @monster = Monster.find(params[:monster_id])
    @curse = Curse.new(curse_params)
    @curse.monster = @monster
    if @curse.save
      redirect_to house_path(@monster.house)
    else
      @powers = Power.where.not(id: @monster.powers).order(name: :asc)
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def curse_params
    params.require(:curse).permit(:power_id)
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController

  # '/houses/1'
  # '/houses/:id'
  def show
    @house = House.find(params[:id])
    @monster = Monster.new
  end
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController

  # 'houses/1/monsters/new'
  # 'houses/:house_id/monsters/new'
  def new
    @monster = Monster.new
    @house = House.find(params[:house_id])
  end

  # 'houses/1/monsters'
  # POST 'houses/:house_id/monsters'
  def create
    @house = House.find(params[:house_id])
    @monster = Monster.new(monster_params)
    @monster.house = @house
    if @monster.save
      redirect_to house_path(@house)
    else
      render 'houses/show', status: :unprocessable_entity
    end
  end

  def destroy
    @monster = Monster.find(params[:id])
    @monster.destroy
    redirect_to house_path(@monster.house), status: :see_other
  end

  private

  def monster_params
    params.require(:monster).permit(:name, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @houses = House.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/curses_helper.rb
module CursesHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/curses/new.html.erb
<div class="container">
  <h1>Add a Power</h1>
  <%= simple_form_for [@monster, @curse] do |f| %>
    <%= f.association :power, collection: @powers, include_blank: false  %>
    <%= f.submit 'Add', class: 'btn btn-danger' %>
  <% end %>
</div>

app/views/houses/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @house.banner_url %>);">
  <div class="container">
    <h1><%= @house.name %></h1>
    <%= link_to 'Condemn', new_house_monster_path(@house), class: 'btn btn-danger mt-2'  %>
  </div>
</div>
<div class="container">
  <div class="cards mt-3">
    <% @house.monsters.each do |monster| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= monster.photo.attached? ? cl_image_path(monster.photo.key) : monster.image_url %>)">
        <%= monster.name %>
        <%= link_to new_monster_curse_path(monster), class: 'card-link card-add-link' do %>
          <i class="fa-solid fa-bolt"></i>
        <% end %>
        <%= link_to monster_path(monster), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'card-link card-remove-link' do %>
          <i class="fa-solid fa-cross"></i>
        <% end %>
        <div class="card-tags">
          <% monster.powers.each do |power| %>
            <span><%= power.name %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="row justify-content-center my-3">
    <div class="col-12 col-md-8 col-lg-6">
      <%= render 'monsters/form', house: @house, monster: @monster  %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MonsterSlayers1885</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/monsters/_form.html.erb
<%= simple_form_for [house, monster] do |f| %>
  <%= f.input :name %>
  <!-- NO more string URLs -->
  <%#= f.input :image_url %>
  <%= f.input :photo, as: :file %>
  <%= f.submit 'Condemn', class: 'btn btn-danger mt-2' %>
<% end %>

app/views/monsters/new.html.erb
<div class="container">
  <h1>Condemn a Monster</h1>
  <%= render 'monsters/form', monster: @monster, house: @house %>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.psychologicalscience.org/redesign/wp-content/uploads/2022/01/How-Haunted-Houses-Measure-Fear-Web-1024x431.jpg);">
  <div class="container">
    <h1>Monster Slayers</h1>
  </div>
</div>
<div class="container my-5">
  <div class="cards">
    <% @houses.each do |house| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= house.banner_url %>)">
        <%= link_to house.name, house_path(house), class: 'text-decoration-none text-white'%>
      </div>
    <% end %>
  </div>
</div>